export const navbarHeight = 80;
export const margin = 20;
export const heroHeight = 95;
export const maxWidth = 940;
export const smallUp = 678;
export const mediumUp = 992; // used to be 840
export const mobileSizeMod = 0.66;
export const smallUpQuery = `@media (min-width: ${smallUp}px)`;
export const mediumUpQuery = `@media (min-width: ${mediumUp}px)`;
