name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install and lint
        run: |
          npm install
          CI=true npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install and test
        run: |
          npm install
          CI=true npm test
  visual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install and visual test
        run: |
          npm install
          CI=true npm run visual
      - name: upload visual test results
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: visual_tests
          path: .loki
  build-and-deploy:
    needs: [lint, test, visual]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
    - uses: actions/checkout@master
    - name: npm install, build, and deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build
        BASE_BRANCH: develop
